spring:
  datasource:
   url: jdbc:h2:mem:codingtest;MODE=MYSQL
   username: sa
   password: 
   driverClassName: org.h2.Driver
  jpa:
   spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
   hibernate.ddl-auto: none
  h2:
   console.enabled: true
server:
  port: 8081

error:
  include-message: always
  include-binding-errors: always
  include-stacktrace: on_trace_param
  include-exception: false

spring.jpa.open-in-view: false